dj_blog/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

dj_blog/dj_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

dj_blog/blog/models.py
from django.db import models

# Create your models here.

dj_blog/blog/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	
	return render(request, "blog/index.html")

dj_blog/blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
            Blog
        {% endblock title %}
    </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/styles.css' %}" />
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
                <a href="{% url 'blog:index' %}" class="navbar-brand">
                    Blog
                </a>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    <footer class="page-footer">
        <hr>
        <div class="container">
            &copy; Awesome Inc U. Bootcamp 2016
        </div>
    </footer>

    <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

dj_blog/blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block title %}
    {{ block.super }}
    - Index
{% endblock title %}

{% block content %}
    Hello World
{% endblock content %}